##
## Command Viewer Config
## 

## Currently this config will do absolutly nothing, however I want to make sure that is is ready for the 2.1 release. 

commandhighlights:
    - stop
    - reload
    
